# Generated by Django 6.0.2 on 2026-02-04 13:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(help_text='e.g., Family, Honeymoon, Adventure', max_length=100)),
                ('budget', models.CharField(choices=[('Low', 'Low Budget'), ('Medium', 'Medium Budget'), ('High', 'Luxury Budget')], max_length=20)),
                ('best_time', models.CharField(max_length=100)),
                ('bad_time', models.CharField(blank=True, max_length=100)),
                ('state_image', models.URLField(help_text='URL to destination image')),
                ('languages', models.JSONField(default=list, help_text='List of local languages and phrases')),
                ('stay_cost', models.DecimalField(decimal_places=2, help_text='Average cost per night', max_digits=8)),
                ('food_cost', models.DecimalField(decimal_places=2, help_text='Average cost per day', max_digits=8)),
                ('transport_cost', models.DecimalField(decimal_places=2, help_text='Average transport cost', max_digits=8)),
                ('activities_cost', models.DecimalField(decimal_places=2, help_text='Average activities cost', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=100)),
                ('price', models.CharField(help_text='Price range, e.g., ₹60–120', max_length=50)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='home.destination')),
            ],
        ),
        migrations.CreateModel(
            name='TravelVlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('local-insider', 'Local Insider'), ('budget-travel', 'Budget Travel'), ('food-tour', 'Food Tour'), ('adventure', 'Adventure'), ('cultural', 'Cultural')], max_length=20)),
                ('thumbnail', models.URLField()),
                ('video_url', models.URLField()),
                ('duration', models.CharField(help_text='e.g., 12:34', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('tags', models.JSONField(default=list, help_text='List of tags')),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to='home.destination')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('travelers_count', models.PositiveIntegerField(default=1)),
                ('daily_budget', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_type', models.CharField(help_text='e.g., Family, Solo, Couple', max_length=50)),
                ('interests', models.JSONField(default=list, help_text='List of interests')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('preferred_budget', models.CharField(choices=[('Low', 'Budget Traveler'), ('Medium', 'Mid-range'), ('High', 'Luxury Traveler')], default='Medium', max_length=20)),
                ('travel_types', models.JSONField(default=list, help_text='Preferred travel types')),
                ('trips_taken', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_destinations', models.ManyToManyField(blank=True, to='home.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pros', models.TextField(blank=True, help_text='What you liked')),
                ('cons', models.TextField(blank=True, help_text='What could be improved')),
                ('visit_date', models.DateField()),
                ('travel_type', models.CharField(help_text='e.g., Family, Solo, Business', max_length=50)),
                ('recommended_budget', models.CharField(choices=[('Low', 'Low Budget'), ('Medium', 'Medium Budget'), ('High', 'Luxury Budget')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('helpful_votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('activities', models.JSONField(default=list, help_text='List of activities for the day')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='home.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
