# Generated by Django 6.0.2 on 2026-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelvlog',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file', null=True, upload_to='vlogs/'),
        ),
        migrations.AlterField(
            model_name='travelvlog',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', null=True),
        ),
    ]
