# Generated by Django 6.0.2 on 2026-02-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_travelvlog_video_file_alter_travelvlog_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelvlog',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 12:34', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='travelvlog',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
