# Generated by Django 6.0.2 on 2026-02-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_travelvlog_duration_alter_travelvlog_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='languages',
            field=models.CharField(default='', help_text='Comma-separated languages (e.g. English, Hindi)', max_length=200),
        ),
    ]
